name: 'request-reviewer'
description: 'Request Random Reviewer'

inputs:
  region:
    required: true
  env:
    required: true

outputs:
  lang:
    description: 'First value'
  service:
    description: 'Second value'

runs:
  using: 'node20'
  main: 'index.js'
