crtfc_key:
  in: query
  name: crtfc_key
  description: 발급받은 DART OpenAPI 인증키(40자리)
  required: true
  schema:
    type: string
    example: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

corp_code:
  name: corp_code
  in: query
  description: 공시대상회사의 고유번호(8자리)
  required: true
  schema:
    type: string
    example: "00126380"
    maxLength: 8

bsns_year:
  name: bsns_year
  in: query
  description: 사업연도(4자리) ※ 2015년 이후 부터 정보제공
  required: true
  schema:
    type: string
    example: "2019"
    maxLength: 4

reprt_code:
  name: reprt_code
  in: query
  description: |
    보고서 코드

    - 11011 : 사업보고서<br/>
    - 11012 : 반기보고서<br/>
    - 11013 : 1분기보고서<br/>
    - 11014 : 3분기보고서
  required: true
  schema:
    type: string
    example: "11011"
    maxLength: 5

bgn_de:
  name: bgn_de
  in: query
  description: |
    시작일

    검색시작 접수일자(YYYYMMDD)<br/>
    1) 기본값 : 종료일(end_de)<br/>
    2) 고유번호(corp_code)가 없는 경우 검색기간은 3개월로 제한
  required: true
  schema:
    type: string
    example: "20240601"
    maxLength: 8

end_de:
  name: end_de
  in: query
  description: |
    종료일

    검색종료 접수일자(YYYYMMDD)
    1) 기본값 : 당일
  required: true
  schema:
    type: string
    example: "20240601"
    maxLength: 8

fs_div:
  name: fs_div
  in: query
  description: |
    개별/연결 구분

    - CFS : 연결재무제표<br/>
    - OFS : 재무제표
  required: true
  schema:
    type: string
    enum: ["CFS", "OFS"]
    example: "CFS"

sj_div:
  name: sj_div
  in: query
  description: |
    재무제표구분
    <table>
      <th>
        <td>재무제표구분</td>
        <td>재무제표명칭</td>
        <td>개별/연결</td>
        <td>표시방법</td>
        <td>세전 세후</td>
      </th>
      <tr>
        <td>BS1</td>
        <td>재무상태표</td>
        <td>연결</td>
        <td>유동/비유동법</td>
        <td></td>
      </tr>
      <tr>
        <td>BS2</td>
        <td>재무상태표</td>
        <td>개별</td>
        <td>유동/비유동법</td>
        <td></td>
      </tr>
      <tr>
        <td>BS3</td>
        <td>재무상태표</td>
        <td>연결</td>
        <td>유동성배열법</td>
        <td></td>
      </tr>
      <tr>
        <td>BS4</td>
        <td>재무상태표</td>
        <td>개별</td>
        <td>유동성배열법</td>
        <td></td>
      </tr>
      <tr>
        <td>IS1</td>
        <td>별개의 손익계산서</td>
        <td>연결</td>
        <td>기능별분류</td>
        <td></td>
      </tr>
      <tr>
        <td>IS2</td>
        <td>별개의 손익계산서</td>
        <td>개별</td>
        <td>기능별분류</td>
        <td></td>
      </tr>
      <tr>
        <td>IS3</td>
        <td>별개의 손익계산서</td>
        <td>연결</td>
        <td>성격별분류</td>
        <td></td>
      </tr>
      <tr>
        <td>IS4</td>
        <td>별개의 손익계산서</td>
        <td>개별</td>
        <td>성격별분류</td>
        <td></td>
      </tr>
      <tr>
        <td>CIS1</td>
        <td>포괄손익계산서</td>
        <td>연결</td>
        <td>세후</td>
        <td></td>
      </tr>
      <tr>
        <td>CIS2</td>
        <td>포괄손익계산서</td>
        <td>개별</td>
        <td>세후</td>
        <td></td>
      </tr>
      <tr>
        <td>CIS3</td>
        <td>포괄손익계산서</td>
        <td>연결</td>
        <td>세전</td>
        <td></td>
      </tr>
      <tr>
        <td>CIS4</td>
        <td>포괄손익계산서</td>
        <td>개별</td>
        <td>세전</td>
        <td></td>
      </tr>
      <tr>
        <td>DCIS1</td>
        <td>단일 포괄손익계산서</td>
        <td>연결</td>
        <td>기능별분류</td>
        <td>세후포괄손익</td>
      </tr>
      <tr>
        <td>DCIS2</td>
        <td>단일 포괄손익계산서</td>
        <td>개별</td>
        <td>기능별분류</td>
        <td>세후포괄손익</td>
      </tr>
      <tr>
        <td>DCIS3</td>
        <td>단일 포괄손익계산서</td>
        <td>연결</td>
        <td>기능별분류</td>
        <td>세전</td>
      </tr>
      <tr>
        <td>DCIS4</td>
        <td>단일 포괄손익계산서</td>
        <td>개별</td>
        <td>기능별분류</td>
        <td>세전</td>
      </tr>
      <tr>
        <td>DCIS5</td>
        <td>단일 포괄손익계산서</td>
        <td>연결</td>
        <td>성격별분류</td>
        <td>세후포괄손익</td>
      </tr>
      <tr>
        <td>DCIS6</td>
        <td>단일 포괄손익계산서</td>
        <td>개별</td>
        <td>성격별분류</td>
        <td>세후포괄손익</td>
      </tr>
      <tr>
        <td>DCIS7</td>
        <td>단일 포괄손익계산서</td>
        <td>연결</td>
        <td>성격별분류</td>
        <td>세전</td>
      </tr>
      <tr>
        <td>DCIS8</td>
        <td>단일 포괄손익계산서</td>
        <td>개별</td>
        <td>성격별분류</td>
        <td>세전</td>
      </tr>
      <tr>
        <td>CF1</td>
        <td>현금흐름표</td>
        <td>연결</td>
        <td>직접법</td>
        <td></td>
      </tr>
      <tr>
        <td>CF2</td>
        <td>현금흐름표</td>
        <td>개별</td>
        <td>직접법</td>
        <td></td>
      </tr>
      <tr>
        <td>CF3</td>
        <td>현금흐름표</td>
        <td>연결</td>
        <td>간접법</td>
        <td></td>
      </tr>
      <tr>
        <td>CF4</td>
        <td>현금흐름표</td>
        <td>개별</td>
        <td>간접법</td>
        <td></td>
      </tr>
      <tr>
        <td>SCE1</td>
        <td>자본변동표</td>
        <td>연결</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>SCE2</td>
        <td>자본변동표</td>
        <td>개별</td>
        <td></td>
        <td></td>
      </tr>
    </table>
  required: true
  schema:
    type: string
    enum:
      [
        "BS1",
        "BS2",
        "BS3",
        "BS4",
        "IS1",
        "IS2",
        "IS3",
        "IS4",
        "CIS1",
        "CIS2",
        "CIS3",
        "CIS4",
        "DCIS1",
        "DCIS2",
        "DCIS3",
        "DCIS4",
        "DCIS5",
        "DCIS6",
        "DCIS7",
        "DCIS8",
        "CF1",
        "CF2",
        "CF3",
        "CF4",
        "SCE1",
        "SCE2",
      ]
    example: "BS1"
