crtfc_key:
  in: query
  name: crtfc_key
  description: 발급받은 DART OpenAPI 인증키(40자리)
  required: true
  schema:
    type: string
    example: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

corp_code:
  name: corp_code
  in: query
  description: 공시대상회사의 고유번호(8자리)
  required: true
  schema:
    type: string
    example: "00126380"
    maxLength: 8

bsns_year:
  name: bsns_year
  in: query
  description: 사업연도(4자리) ※ 2015년 이후 부터 정보제공
  required: true
  schema:
    type: string
    example: "2019"
    maxLength: 4

reprt_code:
  name: reprt_code
  in: query
  description: |
    보고서 코드

    - 11011 : 사업보고서<br/>
    - 11012 : 반기보고서<br/>
    - 11013 : 1분기보고서<br/>
    - 11014 : 3분기보고서
  required: true
  schema:
    type: string
    example: "11011"
    maxLength: 5

bgn_de:
  name: bgn_de
  in: query
  description: |
    시작일

    검색시작 접수일자(YYYYMMDD)<br/>
    1) 기본값 : 종료일(end_de)<br/>
    2) 고유번호(corp_code)가 없는 경우 검색기간은 3개월로 제한
  required: true
  schema:
    type: string
    example: "20240601"
    maxLength: 8

end_de:
  name: end_de
  in: query
  description: |
    종료일

    검색종료 접수일자(YYYYMMDD)
    1) 기본값 : 당일
  required: true
  schema:
    type: string
    example: "20240601"
    maxLength: 8

fs_div:
  name: fs_div
  in: query
  description: |
    개별/연결 구분

    - CFS : 연결재무제표<br/>
    - OFS : 재무제표
  required: true
  schema:
    type: string
    enum: ["CFS", "OFS"]
    example: "CFS"

sj_div:
  name: sj_div
  in: query
  description: |
    재무제표구분

    | 재무제표구분 | 재무제표명칭 | 개별/연결 | 표시방법 | 세전 세후 |
    |-----|-----|-------|
    | BS1 | 재무상태표 | 연결 | 유동/비유동법 | |
    | BS2 | 재무상태표 | 개별 | 유동/비유동법 | |
    | BS3 | 재무상태표 | 연결 | 유동성배열법 | |
    | BS4 | 재무상태표 | 개별 | 유동성배열법 | |
    | IS1 | 별개의 손익계산서 | 연결 | 기능별분류 | |
    | IS2 | 별개의 손익계산서 | 개별 | 기능별분류 | |
    | IS3 | 별개의 손익계산서 | 연결 | 성격별분류 | |
    | IS4 | 별개의 손익계산서 | 개별 | 성격별분류 | |
    | CIS1 | 포괄손익계산서 | 연결 | 세후 | |
    | CIS2 | 포괄손익계산서 | 개별 | 세후 | |
    | CIS3 | 포괄손익계산서 | 연결 | 세전 | |
    | CIS4 | 포괄손익계산서 | 개별 | 세전 | |
    | DCIS1 | 단일 포괄손익계산서 | 연결 | 기능별분류 | 세후포괄손익 |
    | DCIS2 | 단일 포괄손익계산서 | 개별 | 기능별분류 | 세후포괄손익 |
    | DCIS3 | 단일 포괄손익계산서 | 연결 | 기능별분류 | 세전 |
    | DCIS4 | 단일 포괄손익계산서 | 개별 | 기능별분류 | 세전 |
    | DCIS5 | 단일 포괄손익계산서 | 연결 | 성격별분류 | 세후포괄손익 |
    | DCIS6 | 단일 포괄손익계산서 | 개별 | 성격별분류 | 세후포괄손익 |
    | DCIS7 | 단일 포괄손익계산서 | 연결 | 성격별분류 | 세전 |
    | DCIS8 | 단일 포괄손익계산서 | 개별 | 성격별분류 | 세전 |
    | CF1 | 현금흐름표 | 연결 | 직접법 | |
    | CF2 | 현금흐름표 | 개별 | 직접법 | |
    | CF3 | 현금흐름표 | 연결 | 간접법 | |
    | CF4 | 현금흐름표 | 개별 | 간접법 | |
    | SCE1 | 자본변동표 | 연결 | | |
    | SCE2 | 자본변동표 | 개별 | | |

  required: true
  schema:
    type: string
    enum:
      [
        "BS1",
        "BS2",
        "BS3",
        "BS4",
        "IS1",
        "IS2",
        "IS3",
        "IS4",
        "CIS1",
        "CIS2",
        "CIS3",
        "CIS4",
        "DCIS1",
        "DCIS2",
        "DCIS3",
        "DCIS4",
        "DCIS5",
        "DCIS6",
        "DCIS7",
        "DCIS8",
        "CF1",
        "CF2",
        "CF3",
        "CF4",
        "SCE1",
        "SCE2",
      ]
    example: "BS1"
