personal_secret_key:
  in: header
  name: personalseckey
  description: |
    고객 식별키

    [법인 필수] 제휴사 회원 관리를 위한 고객식별키
  required: false
  schema:
    type: string
    example: 1234567

tr_cont:
  in: header
  name: tr_cont
  description: |
    연속 거래 여부

    공백 : 초기 조회<br/>
    N: 다음 데이터 조회 (output header의 tr_cont가 M일 경우)
  required: false
  schema:
    type: string
    default: ""
    example: ""

customer_type:
  in: header
  name: custtype
  description: |
    고객타입

    B : 법인<br/>
    P : 개인
  required: false
  schema:
    type: string
    enum: ["B", "P"]
    default: P
    example: "B"

sequence_no:
  in: header
  name: seq_no
  description: |
    일련번호

    [법인 필수] 001
  required: false
  schema:
    type: string
    example: "001"

mac_address:
  in: header
  name: mac_address
  description: |
    맥주소

    법인고객 혹은 개인고객의 Mac address 값
  required: false
  schema:
    type: string

phone_number:
  in: header
  name: phone_number
  description: |
    핸드폰번호

    [법인 필수] 제휴사APP을 사용하는 경우 사용자(회원) 핸드폰번호<br/>
    ex) 01011112222 (하이픈 등 구분값 제거)
  required: false
  schema:
    type: string
    example: 01011112222

ip_address:
  in: header
  name: ip_address
  description: |
    접속 단말 공인 IP

    [법인 필수] 사용자(회원)의 IP Address
  required: false
  schema:
    type: string
    example: 192.168.0.12

hashkey:
  in: header
  name: hashkey
  description: |
    해쉬키

    [POST API 대상] Client가 요청하는 Request Body를 hashkey api로 생성한 Hash값<br/>
    * API문서 > hashkey 참조
  required: false
  schema:
    type: string
    example: 1234567

gt_uid:
  in: header
  name: gt_uid
  description: |
    Global UID

    [법인 필수] 거래고유번호로 사용하므로 거래별로 UNIQUE해야 함
  required: false
  schema:
    type: string
    example: 1234567

fid_input_iscd:
  in: query
  name: fid_input_iscd
  description: |
    FID 입력 종목코드

    0000:전체, 0001:코스피, 1001:코스닥, 2001:코스피200.. 등<br/>
    포탈 (FAQ : 종목정보 다운로드(국내) - 업종코드 참조)
  required: true
  schema:
    type: string
    example: "0001"
